[package]
name = "reef_tracing"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
serde = { workspace = true }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3.20" }

settings = { path = "../settings" }